# Generated by Django 5.2.8 on 2025-11-15 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desktop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('date', models.DateField()),
                ('dateDelivery', models.DateField()),
                ('code', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desktop.product')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desktop.orderlocation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desktop.user')),
            ],
        ),
    ]
