# Generated by Django 5.2.8 on 2025-11-15 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desktop', '0002_neworder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neworder',
            name='code',
        ),
        migrations.RemoveField(
            model_name='neworder',
            name='num',
        ),
        migrations.RemoveField(
            model_name='neworder',
            name='user',
        ),
    ]
