# Generated by Django 5.2.6 on 2026-03-26 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=55)),
                ('price', models.PositiveIntegerField()),
                ('seller', models.CharField(max_length=30)),
                ('creator', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('discount', models.PositiveIntegerField()),
                ('count', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='./Images')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=10)),
                ('surname', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('patronymic', models.CharField(max_length=30)),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('date', models.DateField()),
                ('date_delivery', models.DateField()),
                ('code', models.IntegerField()),
                ('status', models.CharField(max_length=30)),
                ('order_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desktop.orderlocation')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desktop.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desktop.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ManyToManyField(through='desktop.OrderDetails', to='desktop.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desktop.user'),
        ),
    ]
