# Generated by Django 5.2.6 on 2025-11-23 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=10)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('counter', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('seller', models.CharField(max_length=50)),
                ('creator', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('discount', models.IntegerField()),
                ('count', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='Images')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desktop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('date', models.DateField()),
                ('dateDelivery', models.DateField()),
                ('code', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('order', models.ManyToManyField(to='desktop.cart')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desktop.orderlocation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desktop.user')),
            ],
        ),
    ]
