# Generated by Django 5.2.6 on 2026-02-03 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desktop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=40)),
                ('counter', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('seller', models.CharField(max_length=30)),
                ('creator', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=30)),
                ('discount', models.IntegerField()),
                ('count', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='Product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('date', models.DateField()),
                ('dateDelivery', models.DateField()),
                ('code', models.IntegerField()),
                ('status', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desktop.user')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desktop.orderlocation')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desktop.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desktop.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='orders',
            field=models.ManyToManyField(through='desktop.OrderDetails', to='desktop.product'),
        ),
    ]
