# Generated by Django 5.2.6 on 2025-11-19 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desktop', '0003_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('dateDelivery', models.DateField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desktop.product')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desktop.orderlocation')),
            ],
        ),
    ]
